<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit926b7819947f12f2ee99156aa1ee605a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'A' => 
        array (
            'Azark\\CookMaster\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Azark\\CookMaster\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit926b7819947f12f2ee99156aa1ee605a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit926b7819947f12f2ee99156aa1ee605a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit926b7819947f12f2ee99156aa1ee605a::$classMap;

        }, null, ClassLoader::class);
    }
}
